# Generated by Django 6.0 on 2025-12-14 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Especialidad')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción (Opcional)')),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, unique=True, verbose_name='Cédula (V- / E-)')),
                ('numero_historia', models.CharField(max_length=20, unique=True, verbose_name='Nº Historia Clínica')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono Celular')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(verbose_name='Dirección de Habitación')),
                ('tipo_sangre', models.CharField(blank=True, max_length=5, verbose_name='Tipo de Sangre')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias Conocidas')),
                ('enfermedades_cronicas', models.TextField(blank=True, verbose_name='Enfermedades Crónicas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos_pacientes/')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField()),
                ('realizada', models.BooleanField(default=False)),
                ('diagnostico', models.TextField(blank=True)),
                ('tratamiento', models.TextField(blank=True)),
                ('sintomas', models.TextField(blank=True, verbose_name='Observaciones / Signos Vitales')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_como_medico', to=settings.AUTH_USER_MODEL, verbose_name='Médico Tratante')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('medico', 'Médico'), ('secretaria', 'Secretaria/Recepción'), ('administrador', 'Administrador'), ('contador', 'Contador'), ('paciente', 'Paciente (Usuario Web)')], default='paciente', max_length=20)),
                ('cedula_identidad', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Cédula (C.I.)')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('codigo_colegio_medicos', models.CharField(blank=True, max_length=20, verbose_name='Cód. Colegio Médicos')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miapp.especialidad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
