# Generated by Django 6.0 on 2025-12-15 20:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoImportante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Información Importante', max_length=100)),
                ('mensaje', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarruselImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('imagen', models.ImageField(upload_to='carrusel/')),
                ('overlay', models.CharField(choices=[('0', '0%'), ('0.3', '30%'), ('0.5', '50%'), ('0.7', '70%')], default='0.5', max_length=5)),
                ('orden', models.IntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=255)),
                ('respuesta', models.TextField()),
                ('orden', models.IntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso (Consulta/Cirugía)'), ('egreso', 'Egreso (Gasto Operativo)'), ('nomina', 'Pago de Nómina'), ('impuesto', 'Pago de Impuestos (SENIAT/Alcaldía)')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Concepto')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('referencia', models.CharField(blank=True, help_text='Nro de Factura o Referencia Bancaria', max_length=50)),
                ('es_divisa', models.BooleanField(default=False, verbose_name='¿Es en Dólares?')),
                ('tasa_cambio', models.DecimalField(decimal_places=2, default=0, help_text='Tasa BCV del día', max_digits=10)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, unique=True, verbose_name='Cédula')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True)),
                ('alergias', models.TextField(blank=True, default='Ninguna')),
                ('enfermedades_cronicas', models.TextField(blank=True, default='Ninguna')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente_perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicacion', models.TextField(help_text='Tratamiento, medicina a suministrar o cuidados.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ejecutada', models.BooleanField(default=False)),
                ('nota_enfermeria', models.TextField(blank=True, help_text='Observaciones de la enfermera al aplicar')),
                ('fecha_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('enfermera_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_atendidas', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='resultados/')),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('realizada', models.BooleanField(default=False)),
                ('medico', models.ForeignKey(limit_choices_to={'perfilusuario__rol': 'medico'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, null=True, unique=True)),
                ('rol', models.CharField(choices=[('medico', 'Médico'), ('secretaria', 'Secretaria'), ('contador', 'Administrativo/Contable'), ('enfermera', 'Enfermera'), ('gerente', 'Jefe de Clínica')], max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miapp.especialidad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalAutorizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, unique=True, verbose_name='Cédula Autorizada')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('rol', models.CharField(choices=[('medico', 'Médico'), ('secretaria', 'Secretaria'), ('contador', 'Administrativo/Contable'), ('enfermera', 'Enfermera'), ('gerente', 'Jefe de Clínica')], max_length=20)),
                ('usado', models.BooleanField(default=False, help_text='Marcará si ya se registró el usuario')),
                ('especialidad_asignada', models.ForeignKey(blank=True, help_text='Solo para médicos', null=True, on_delete=django.db.models.deletion.SET_NULL, to='miapp.especialidad')),
            ],
        ),
    ]
