# Generated by Django 6.0 on 2025-12-14 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='codigo_colegio_medicos',
        ),
        migrations.AddField(
            model_name='paciente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente_perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_medico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cita',
            name='sintomas',
            field=models.TextField(blank=True, verbose_name='Signos Vitales / Observaciones'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cedula',
            field=models.CharField(max_length=15, unique=True, verbose_name='Cédula (V-/E-)'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='enfermedades_cronicas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_historia',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nº Historia'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_sangre',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='cedula_identidad',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='C.I.'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('medico', 'Médico'), ('secretaria', 'Secretaria/Recepción'), ('administrador', 'Administrador'), ('contador', 'Contador'), ('paciente', 'Paciente')], default='paciente', max_length=20),
        ),
    ]
