# Generated by Django 6.0 on 2025-12-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='diagnostico',
            field=models.TextField(blank=True, help_text='Conclusión médica', null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='sintomas',
            field=models.TextField(blank=True, help_text='Descripción de lo que siente el paciente', null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='tratamiento',
            field=models.TextField(blank=True, help_text='Medicamentos y recomendaciones', null=True),
        ),
    ]
